version: '3'
services:
  api:
    build: .
    depends_on:
      - db-members
      - db-actions
      - db-posts
    ports:
      - "80:80"
    environment:
      USER: postgres
      PASSWORD: postgres
  db-members:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: members
    volumes:
      - ./database/members:/var/lib/postgresql/data
  db-actions:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: actions
    volumes:
      - ./database/actions:/var/lib/postgresql/data
  db-posts:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: posts
    volumes:
      - ./database/posts:/var/lib/postgresql/data
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: members
    volumes:
      - ./database:/var/lib/postgresql/data