version: '3'
services:
  api:
    build: .
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      HOST: database
      PORT: 5432
      USER: postgres
      PASSWORD: postgres
      DB: postgres
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./database:/var/lib/postgresql/data