version: '3'
services:
  api:
    build: .
    depends_on:
      - db-members
      - db-actions
      - db-posts
    ports:
      - "8080:80"
    environment:
      USER: root
      PASSWORD: mariadb
  db-members:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: members
    volumes:
      - ./database/members:/var/lib/mysql
  db-actions:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: actions
    volumes:
      - ./database/actions:/var/lib/mysql
  db-posts:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: posts
    volumes:
      - ./database/posts:/var/lib/mysql
